Generate new report function
YahyoMahmudov/E2E-Testing pull request #12
Opened 2024-03-27 04:41 UTC by YahyoMahmudov

2024-03-27 06:50 UTC, jkalandarov requested changes

2024-03-27 06:50 UTC, jkalandarov commented on cucumber.js
> +    tags: '@report',
Do you want to run tests with `@report` tag only?

2024-03-27 06:50 UTC, jkalandarov commented on cucumber.js
> +    format: ['./reporter.js'],
Does this change also work for Ilhom?

2024-03-27 06:50 UTC, jkalandarov commented on src/helper/wrapper/playwrightWrappers.ts
> +      state: 'attached',
what's the difference between `visible` state and `attached` state?

2024-03-27 06:50 UTC, jkalandarov commented on src/helper/wrapper/playwrightWrappers.ts
> +  }
What if you have to press the TAB button are you going to create another method for that action? Maybe, isn't it better to create a universal method that accepts the button name as a parameter and clicks on it, if that button doesn't exist return an error?

2024-03-27 06:50 UTC, jkalandarov commented on src/helper/wrapper/playwrightWrappers.ts
> +  async scrollDown() {
Have you checked this method: https://playwright.dev/docs/api/class-locator#locator-scroll-into-view-if-needed ?

2024-03-27 06:50 UTC, jkalandarov commented on src/helper/wrapper/playwrightWrappers.ts
> +  async waitForElementText(element: Locator, expectedText: string): Promise<boolean> {
method name is confusing. waitForElementTextVisible? waitForElementTextDisappear?

2024-03-27 06:50 UTC, jkalandarov commented on src/helper/wrapper/playwrightWrappers.ts
> +    return false;
I am sure you can simplify these blocks of code using Playwright APIs.

2024-03-27 06:50 UTC, jkalandarov commented on src/hooks/hooks.ts
>    browser = await invokeBrowser(false);
Since when `invokeBrowser` is accepting a boolean parameter?

2024-03-27 06:50 UTC, jkalandarov commented on src/pages/reportsPage.ts
> +    }
You can simplify these block of codes.

2024-03-27 06:50 UTC, jkalandarov commented on src/pages/reportsPage.ts
> +    }
You can simplify these blocks of code.

2024-03-27 06:50 UTC, jkalandarov commented on src/test/features/generateReport.feature
> +        Then User is in Dashboard page
One step definition should check if user is in particular page.

2024-03-27 06:50 UTC, jkalandarov commented on src/test/features/generateReport.feature
> +        When User navigates to Reports tab
One step definition should be responsible for navigating user to ANY given page.

2024-03-27 06:50 UTC, jkalandarov commented on src/test/features/generateReport.feature
> +        And User clicks New Report button
One step definition should be able to click on ANY elements.

2024-03-27 06:50 UTC, jkalandarov commented on src/test/features/generateReport.feature
> +        And User clicks Save button
You should refactor using step definitions.

2024-03-27 06:50 UTC, jkalandarov commented on src/test/steps/generateReportSteps.ts
> +When('User navigates to Reports tab', async function () {
One step definition should be responsible for navigating user to ANY given page.

2024-03-27 06:50 UTC, jkalandarov commented on src/test/steps/generateReportSteps.ts
> +When('User clicks New Report button', async function () {
One step definition should be able to click on ANY elements.

2024-03-27 06:50 UTC, jkalandarov commented on src/test/steps/generateReportSteps.ts
> +When('User enters report name as {string}', async function (reportName) {
One step definition should be able to type into input element.

2024-03-27 06:50 UTC, jkalandarov commented on src/test/steps/generateReportSteps.ts
> +When('User clicks Save button', async function () {
One step definition should be able to click on ANY elements.

2024-03-29 04:35 UTC, YahyoMahmudov commented on src/hooks/hooks.ts
>    browser = await invokeBrowser(false);
It accepts isHeadless value:
```
export const invokeBrowser = (isHeadless: boolean) => {
  const browserType = process.env.BROWSER;
  switch (browserType) {
    case 'chrome':
      return chromium.launch({ headless: isHeadless });
    case 'firefox':
      return firefox.launch({ headless: isHeadless });
    case 'webkit':
      return webkit.launch({ headless: isHeadless });
    default:
      throw new Error('Please set the proper browser');
  }
};
```

2024-03-29 05:39 UTC, jkalandarov requested changes
In general, I am happy with the new changes. However, there a few places that need refactoring.

2024-03-29 05:39 UTC, jkalandarov commented on src/helper/wrapper/playwrightWrappers.ts
> +    expect(pageTitle).toContain(title);
`expect` is a void method that doesn't return any value. It's better to use it inside step definitions. If you want a method to check if a page title is equal to some string you can just simply return a boolean value and assert operation result in step definitions.

2024-03-29 05:39 UTC, jkalandarov commented on src/pages/reportsPage.ts
> +  }
Please try to simplify/refactor this method implementation as it is hard to read and understand what this method is trying to do. Remember, you should not explain to others how something works with words, your code should be self-documenting.

2024-03-30 05:06 UTC, jkalandarov requested changes

2024-03-30 05:06 UTC, jkalandarov commented on src/helper/wrapper/playwrightWrappers.ts
> +      return elementText.trim() === expectedText;
you need only this part of the code. The rest is unnecessary.

2024-03-30 05:06 UTC, jkalandarov commented on src/helper/wrapper/playwrightWrappers.ts
> +  async toCamelCase(input: string): Promise<string> {
Since you're not using `await` you can remove `async`. I don't see any asynchronous operation in your code.

2024-03-30 05:06 UTC, jkalandarov commented on src/test/steps/generateReportSteps.ts
> +  const pageName = await basePage.wrapper.toCamelCase(page);
You've repetitively used `toCamelCase` method. You can refactor and simplify it. For example:
```
const [ casedArgument1, casedArgument2, casedArgument3 ] = toCamelCase(argument1, argument2, argument)
```
You can change `toCamelCase` to accept an array of parameters, transform them into a camel case, and then return an array of transformed arguments.

2024-03-30 06:05 UTC, jkalandarov commented on src/helper/wrapper/playwrightWrappers.ts
>        }
You're invoking `isTextMatch` asynchronously every 1 ms until 30 seconds of timeout. Maybe, you don't need to check text changes every 1 ms? Instead, you could try checking if checking has changed every 100 ms or every second.

2024-03-30 06:05 UTC, jkalandarov commented on cucumber.js
> +    tags: '@report',
If you want to run tests with specific tags, you can pass tags to CLI arguments. Here are the instructions: https://github.com/cucumber/cucumber-js/blob/main/docs/filtering.md#tags

2024-03-30 18:53 UTC, jkalandarov approved these changes

2024-03-31 09:22 UTC, merged