Test cases for Promo code
YahyoMahmudov/E2E-Testing pull request #15
Opened 2024-04-07 18:19 UTC by islamov089

2024-04-08 13:11 UTC, jkalandarov requested changes
Pay attention to code style rules, especially spaces.

2024-04-08 13:11 UTC, jkalandarov commented on src/helper/wrapper/playwrightWrappers.ts
> +    await this.page.waitForLoadState('networkidle');
Official Playwright doc discourages using `'networkidle'` as a waiter: https://playwright.dev/docs/api/class-page#page-wait-for-load-state

2024-04-08 13:11 UTC, jkalandarov commented on src/pages/campaignDetails.ts
add `Page` to page object file name => CampaignDetailsPage.ts
Class names should be snake cases in js/ts.

2024-04-08 13:11 UTC, jkalandarov commented on src/pages/campaignDetails.ts
> +  discountInfo = this.page.locator("(//span[@class='ui-money'])[3]")
not sure what element this locator is referring to. Can you work on naming the locator?

2024-04-08 13:11 UTC, jkalandarov commented on src/pages/promoCodePage.ts
> +  theCodeCanBeUsed = this.page.locator("(//span[text()='The code can be used *']/following::input)[1]")
No need to use articles in variable/property names. what kind of element is `codeCanBeUsed`?

2024-04-08 13:11 UTC, jkalandarov commented on src/pages/promoCodePage.ts
> +    const minute = currentDate.getMinutes().toString().padStart(2, '0');
You can create a separate util class that works with the Date object. You can create various methods inside that class. After all, you can encapsulate that class in your page object.

2024-04-08 13:11 UTC, jkalandarov commented on src/pages/promoCodePage.ts
> +  }
This method merely creates a string in some date format. Therefore it should belong to a different class.

2024-04-08 13:11 UTC, jkalandarov commented on src/pages/promoCodePage.ts
> +    return  this.page.locator(`(//span[text()='${option}'])`)
this method actually doesn't select anything but returns a locator.

2024-04-08 13:11 UTC, jkalandarov commented on src/pages/promoCodePage.ts
> +  public promoCodeCurrency(option: string): Locator {
method name should have a verb, and action in its implementation block.

2024-04-08 13:11 UTC, jkalandarov commented on src/pages/promoCodePage.ts
> +})()
I am confused as to why you are exporting `getPromoCode` and `setPromoCode` variables from here and declaring them by using IIFE.

2024-04-08 13:11 UTC, jkalandarov commented on src/test/features/createPromoCode.feature
> +              And User select dates to "Start Date Input" and "End Date Input" on "Promo Code Page"
user selects which dates?

2024-04-08 13:11 UTC, jkalandarov commented on src/test/features/createPromoCode.feature
> +              And User fills "Search Input" as "Test promo code" on "Dashboard Page"
Do you create `Test promo code` campaign manually before this scenario?

2024-04-14 06:34 UTC, islamov089 commented on src/pages/promoCodePage.ts
> +})()
I wanted to store  Promo code state and use it in another file.

2024-04-18 05:32 UTC, jkalandarov requested changes

2024-04-18 05:32 UTC, jkalandarov commented on src/pages/promoCodePage.ts
> +  public async hoverOverElementAndClickButton(): Promise<void> {
The method name doesn't say on which button this method hovers over and clicks. I assume it should do those actions on any buttons, but the method doesn't accept parameters. So, It is confusing. You should, etheir refactor this method, or rename it.

2024-04-18 05:32 UTC, jkalandarov commented on src/pages/promoCodePage.ts
> +  selectedPromoCodeDates(){
space between

2024-04-18 05:32 UTC, jkalandarov commented on src/test/features/generateReport.feature
Why did you change this file? Is this change included in the scope of your task?

2024-04-18 05:32 UTC, jkalandarov commented on src/test/steps/generateReportSteps.ts
Pay attention you are making unnecessary changes which is extra work for code reviewer.

2024-04-19 12:42 UTC, jkalandarov requested changes
Pay attention to previous comments. You've not changed anything but only linted some files.

2024-04-19 12:42 UTC, jkalandarov commented on src/pages/promoCodePage.ts
> +  public async hoverOverAndClickPayButton(): Promise<void> {
Does this method click on `Activate` button or `Pay` button?

2024-04-19 12:42 UTC, jkalandarov commented on src/pages/promoCodePage.ts
> +  selectedPromoCodeDates() {
The method doesn't select any or perform any action. It just returns a string. Try to find a suitable name for the method.

2024-04-19 12:42 UTC, jkalandarov commented on src/pages/signUpPage.ts
> +  // phoneNumberInput = this.page.locator("(//span[text()='Phone']/following::input)[1]");
Why did you comment the locator?

2024-04-19 12:42 UTC, jkalandarov commented on src/test/features/generateReport.feature
Is there any specific reason for changing this file?

2024-04-21 15:51 UTC, jkalandarov reviewed
Oldingi yozgan kommentariyalarimga etibor bering!!!

2024-04-24 06:50 UTC, jkalandarov requested changes
Ilhom! I've repeated at least 100 times to be attentive. You've been ignoring my comments in every code review. What's the point of conducting a code review in that case?

2024-04-24 06:50 UTC, jkalandarov commented on src/pages/promoCodePage.ts
> +  }
Please look at my previous comment regarding this method.

2024-04-24 06:50 UTC, jkalandarov commented on src/test/steps/createPromoCodeSteps.ts
> +  const datesInput = basePage.promoCodePage.setPromoCodeDates();
`setPromoCodeDates` returns a string. `datesInput` is a confusing name here.

2024-04-24 06:50 UTC, jkalandarov commented on src/test/steps/createPromoCodeSteps.ts
> +  await basePage.wrapper.type(basePage[pageName][endDateInput], datesInput);
`wrapper.type` accepts two parameters. First one is the input name, second is the text to be typed into the input. You are passing inputs to both parameters.

2024-04-24 10:45 UTC, islamov089 commented
@jkalandarov aka campaignWizard.tsni delete qilman deb, campaignWizardPage.ts ni delete qivorgan ekanman boya to'girlab qo'ydim.

2024-04-25 07:30 UTC, jkalandarov approved these changes
Good job!

2024-04-25 11:14 UTC, merged