install eslint, prettier and gherkin-lint
YahyoMahmudov/E2E-Testing pull request #3
Opened 2024-02-26 11:50 UTC by islamov089

2024-02-27 08:54 UTC, jkalandarov commented on config.js
which config file is it?

2024-02-27 08:56 UTC, jkalandarov requested changes

2024-02-27 08:56 UTC, jkalandarov commented on package.json
Have you added scripts to run eslint, gherkin-lint checks? and prettier script to fix issues?

2024-02-27 10:36 UTC, islamov089 commented on config.js
This file belongs to the Allure reporter. I have not finished yet.

2024-02-27 10:41 UTC, islamov089 commented on package.json
yes I just added and tested.

2024-02-27 11:54 UTC, jkalandarov requested changes

2024-02-27 11:54 UTC, jkalandarov commented on config.js
please rename the file as `allure.config.ts` then (or .js).

2024-02-27 12:26 UTC, islamov089 commented on config.js
done

2024-02-28 07:34 UTC, jkalandarov approved these changes

2024-02-28 07:34 UTC, merged